project:
  type: website
  output-dir: docs

website:
  title: "Christopher Kiorlinski"
  navbar:
    left:
      - href: about.qmd
      - hobbies.qmd
      - projectpage.qmd
      - text: "Resume"
        href: ckresumepdf(662025) (1).pdf    
        target: "_blank" 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

