project:
  type: website
  output-dir: docs

website:
  title: "Christopher Kiorlinski"
  navbar:
    left:
      - href: about.qmd
      - href: hobbies.qmd
      - href: projectpage.qmd
      - text: "Resume"
        href: "ckresumepdf(662025) (1).pdf"
        target: "_blank"

format:
  html:
    theme: styles.scss
    mainfont: Funnel Sansq
    toc: true
    page-layout: full

editor: visual
