project:
  type: website
  output-dir: docs

website:
  title: "Christopher Kiorlinski"
  navbar:
    left:
      - href: about.qmd
      - href: hobbies.qmd
      - href: projectpage.qmd
      - text: "Resume"
        href: "ckresumepdf(662025) (1).pdf"
        target: "_blank"

format:
  html:
    theme: flatly
    css: styles.scss     # <-- compile this SCSS _after_ the theme
    toc: true
    page-layout: full

editor: visual
