project:
  type: website
  output-dir: docs

website:
  title: "Christopher Kiorlinski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd
      - projectpage.qmd
      - resume.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

